Add package attribution to Distribution class (Fixes #114) (#115)
* Add package attribution to Distribution class (Fixes #114)

* Add attribute to class

* build-system: restrict to setuptools<77.

This avoids an error while releasing:

```
InvalidDistribution: Metadata is missing required fields: Name, Version
```

Alternatively, we would need to update `constraints.txt` to use Plone 6.0-dev (or 6.1-dev), which has a newer version pin for `twine`:
`twine` 6.1.0+ can handle the metadata generated by setuptools 77.

O, now with still twine 5, I get an error when running `twine check` using Python 3.13:

```
  File "/Users/maurits/community/plone-coredev/6.2/src/plone.distribution/.tox/release-check/lib/python3.13/site-packages/twine/commands/check.py", line 16, in <module>
    import cgi
ModuleNotFoundError: No module named 'cgi'
```

On 3.13 you need `legacy-cgi`.  Maybe twine 5 was missing this dependency?  But when using the latest twine it is fine.
So let's use 6.0-dev so that we get the correct twine version...

---------

Co-authored-by: Maurits van Rees <maurits@vanrees.org>